name: Hello World

on:
  push:
    branches:
      - master

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello World!"
  date:
    runs-on: ubuntu-latest



    steps:
        - name: Print Date
          run: date

        - name: Print Directory Content
          run: ls -l 
