name: Deployment pipeline

on: 
    push:
        branches:
            - master

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
                node-version: '16' 
          - name: Install dependencies
            run: npm install
          - name: lint
            run: npm run eslint
          - name: build
            run: npm run build
          - name: test
            run: npm run test           

          - name: Start Development Server
            run: npm start &
    
          - name: Wait for Development Server
            run: |
              while ! nc -z localhost 8080; do sleep 1; done
              sleep 5  # Adding a slight delay for the server to stabilize
    
          - name: e2e tests
            run: npm run test:e2e